# 관리자 권한 갖기
sudo: required


# 언어 선택
language: generic

# 도커 환경 구성
services:
  - docker

# 스크립트를 실행할 수 있는 환경 구성
before_install:
  - echo "도커 이미지 생성 시작"
  - docker build -t minhyup/docker-react-app -f Dockerfile.dev .

# 실행할 스크립트 (테스트 실행)
script:
  - docker run -e CI=true minhyup/docker-react-app npm run test -- --coverage

# 테스트 성공 후 실행
after_success:
  - echo "도커 환경에서 테스트 성공!"